server:
  port: 8080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  # DB
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=mysql;
    url: jdbc:h2:./mixed_space;DB_CLOSE_DELAY=-1;MODE=mysql;
  # h2
  h2:
    console:
      path: /h2-console #h2嵌入式数据库控制台，可以通过浏览器访问
      enabled: true
      settings:
        # rootrootroot
        web-admin-password: b218ada98873d7ce73d170600ba5bdcd2dd2379e4ba2e84d2bcfa42bb1efd97e0d21f1406650bade15c3f9e06d5b8e2a4fa79a616db52ab31ce49e862127ea75